-- CreateTable
CREATE TABLE "SavedMark" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "kind" TEXT NOT NULL DEFAULT 'SIGNATURE',
    "imagePath" TEXT NOT NULL,
    "posX" REAL NOT NULL DEFAULT 0.6,
    "posY" REAL NOT NULL DEFAULT 0.8,
    "width" REAL NOT NULL DEFAULT 0.24,
    "height" REAL NOT NULL DEFAULT 0.09,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "SavedMark_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
